server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: jsjs9797

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 315362329941-c1n1ckc7kg69e3inl61pqnhrjg92ss1l.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 859445902311841
            client-secret: 3eecc43273c72ee282ce08d4b4ec944a
            scope:
              - email
              - public_profile

          naver:
            client-id: DuXgKGc2usBSF9lcTFBy
            client-secret: mIGWMWB27d
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response