server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: jsjs9797

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 315362329941-c1n1ckc7kg69e3inl61pqnhrjg92ss1l.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

